# .github/workflows/publish.yml
name: Build Shiny Image and Push to Docker Repository

on:
  workflow_call:
    inputs:
      subpath:
        required: true
        type: string


jobs:
  build:
    runs-on: self-hosted
    name: Build and Push
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Docker and Kustomize
        env:
          subpath: ${{ inputs.subpath }}
        run: |
          # add docker file
          tee Dockerfile <<EOF

          FROM registry.container-registry:5000/shiny:1.0.6

          COPY . /srv/shiny-server/${subpath}
          RUN chmod -R 777 /srv/shiny-server/${subpath}

          EOF

      - uses: quartzsoftwarellc/.github/actions/deploy@main
        with:
          image: shiny-${{inputs.subpath}}