# .github/workflows/publish.yml
name: Build Shiny Image and Push to Docker Repository

on:
  workflow_call:
    inputs:
      subpath:
        required: true
        type: string
      env:
        required: false
        type: string
        default: prod


jobs:
  build:
    runs-on: self-hosted
    name: Build and Push
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Docker and Kustomize
        env:
          subpath: ${{ inputs.subpath }}
          env: ${{ inputs.env }}
        run: |
          mkdir -p .argo/shiny
          [[ $env = prod ]] && subdomain="shiny" || subdomain="shiny-dev"

          # add kustomization.yaml
          tee .argo/shiny/kustomization.yaml <<EOF
          resources:
          - "https://github.com/quartzsoftwarellc/shinyapps.git/kustomize"

          nameSuffix: -${subpath}

          commonLabels:
            app: ${subpath}

          patches:
          - patch: |-
              - op: add
                path: /spec/rules/0/http/paths/0/path
                value: /${subpath}
              - op: replace
                path: /spec/rules/0/host
                value: ${subdomain}.quartzsoftware.com
              - op: add
                path: /spec/tls/0
                value:
                  hosts:
                  - ${subdomain}.quartzsoftware.com
                  secretName: ${subdomain}-ingress-tls

            target:
              kind: Ingress

          EOF

          # add docker file
          tee Dockerfile <<EOF

          FROM registry.container-registry:5000/shiny:latest

          COPY . /srv/shiny-server/${subpath}
          RUN chmod -R 777 /srv/shiny-server/${subpath}

          EOF

      - uses: quartzsoftwarellc/.github/actions/deploy@main
        with:
          image: shiny-${{inputs.subpath}}
          kustomize_dir: .argo/shiny
          branch: argo-shiny-${{inputs.env}}
          github_token: ${{ secrets.GITHUB_TOKEN }}